Put in rule to restrict access
glasgow2024/member-portal pull request #17
Opened 2024-06-01 16:39 UTC by balen

members under 16 and apocryphals are not allowed to access the online convention

2024-06-01 16:59 UTC, aJanuary requested changes
We should make it output a specific error for <16. Currently it will point them down the route of buying a membership, when in fact nothing they can do will give them access (unless they invent time travel)

2024-06-02 15:55 UTC, aJanuary submitted a review, later dismissed

2024-06-02 20:19 UTC, balen commented
Put back to review because of merge needed

2024-06-02 20:32 UTC, aJanuary approved these changes

2024-06-03 12:32 UTC, merged